#!/bin/sh


f=$1

analyze() {
	
	minimap2 -a --cs ~/Desktop/Live_analysis/HIST1H3B_A394_A395del_914bp.fasta $f > HIST1H3B_results_A395del_par/raw/alignment_$f.sam && 
	paftools.js sam2paf HIST1H3B_results_A395del_par/raw/alignment_$f.sam > HIST1H3B_results_A395del_par/raw/alignment_$f.paf && 
	sort -k6,6 -k8,8n HIST1H3B_results_A395del_par/raw/alignment_$f.paf > HIST1H3B_results_A395del_par/raw/aln.srt_$f.paf && 
	paftools.js call -l 100 -L 100 HIST1H3B_results_A395del_par/raw/aln.srt_$f.paf > HIST1H3B_results_A395del_par/raw/aln.var_$f.csv
	
}



analyze #> /dev/null 2>&1 #&


cd HIST1H3B_results_A395del_par/raw


awk -F,awk -F '\t' '{print $1,$9,$3,$4,$5,$6,$7,$8,$2,$10,$11,$12}' OFS=, aln.var_$f.csv > aln.var_$f.csv.srt.csv #&

r=aln.var_$f.csv.srt.csv

python3 ~/Desktop/Live_analysis/HIST1H3B_count_variants_pos395_del_par_HiRes "$r" # 2> /dev/null #&


#cat *_count_H3F3A.csv > ../H3F3A_results_unsum.csv 2> /dev/null

#cd ../
#python3 ~/Desktop/ME/Test_structure/H3F3A_summarize_variants_A384_G403_G404_par 2> /dev/null | tee H3F3A_results_deletion_mapping_A384_G403_G404.txt

#end=`date +%s`
#runtime=$((end-start))

#echo H3F3A analysis took $runtime s.





