#!/bin/sh

f=$1

analyze() {
	
	minimap2 -a --cs ~/Desktop/Live_analysis/pTERT_A842del_A865del_1142bp.fasta $f > pTERT_results_A842del_A865del_par/raw/alignment_$f.sam && 
	paftools.js sam2paf pTERT_results_A842del_A865del_par/raw/alignment_$f.sam > pTERT_results_A842del_A865del_par/raw/alignment_$f.paf && 
	sort -k6,6 -k8,8n pTERT_results_A842del_A865del_par/raw/alignment_$f.paf > pTERT_results_A842del_A865del_par/raw/aln.srt_$f.paf && 
	paftools.js call -l 50 -L 50 pTERT_results_A842del_A865del_par/raw/aln.srt_$f.paf > pTERT_results_A842del_A865del_par/raw/aln.var_$f.csv
	
}



analyze > /dev/null 2>&1 #& 

cd pTERT_results_A842del_A865del_par/raw



awk -F,awk -F '\t' '{print $1,$9,$3,$4,$5,$6,$7,$8,$2,$10,$11,$12}' OFS=, aln.var_$f.csv > aln.var_$f.csv.srt.csv #&

r=aln.var_$f.csv.srt.csv

python3 ~/Desktop/Live_analysis/pTERT_count_variants_2A_pos840-847_pos862-868_del_par "$r" 2> /dev/null #&


#cat *_count_pTERT.csv > ../pTERT_results_unsum.csv

#cd ../
#python3 ~/Desktop/ME/Test_structure/pTERT_summarize_variants_2A_pos840-847_pos862-868_par 2> /dev/null | tee pTERT_results_deletion_mapping_A842_A865.txt





